### ISSUE TITLE
More cooler config control

### ISSUE THREAD

**Issue by BrewAndCode** [turbodiesel4598/NuclearCraft#109]
Can you add a configuration that would allow the water cooler to work without the recent change that requires it to touch a casing.  Either that or add another cooler that has zero requirements.  This mechanic totally kills the really large cooler, low reactor, high efficiency setups where the cost is paid into the structure in casings and lots of coolers allow for high efficiency.  with the new mechanic there's lots of dead space in large reactors like this where no block is applicable.  Either that or possibly add in some sort of mod-tweaker to add custom coolers.  

I'm all about the cooler requirements.  but at least one low cooling one (like water) should have zero reqs.

**Comment by QuantumTraverse** [comment]
This is definitely necessary. Creating a >1000% efficient reactor before NC2 was difficult to cool, but not impossible. Now it is, in fact, impossible to cool such a reactor. There simply are too many requirements for coolers which really cannot be met throughout a large (>20 block) reactor.

**Comment by turbodiesel4598** [comment]
I'll add the config that you describe. In fact, I may add a system of config options for each of the coolers to choose how they should behave, i.e. in which configuration they actually work, perhaps with different integers representing the different configurations, and another list of integers for each cooler representing the different blocks with which to interact.

For example, you could choose the redstone cooler to have to be touching two blocks, and then choose which two blocks those are - could be cool :)

That would allow you perhaps recreate super-efficient reactors like in the late 1.7.10 versions. The reason I tuned the system the way I did for 1.10/11.2 is actually because I didn't want efficiencies of that type to be accessible. With the above configs, the system could be very flexible and players could tweak the way the coolers work quite precisely :)

**Comment by turbodiesel4598** [comment]
What I propose above could take some time, so for now, I will just add a simple config option where you can choose whether or not the water cooler needs to be adjacent to casing as initially suggested by BrewAndCode.

**Comment by turbodiesel4598** [comment]
After thinking about the above idea for a while, I've decided against it. NC has moved into an era of design-sharing which would become very messy if different players used different cooler rules. As the original suggestion was implemented long ago, I will close this issue.
