### ISSUE TITLE
Alloy Smelter doesn't accept oredict variants of Graphite Dust (1.11.2)

### ISSUE THREAD

**Issue by turnerlewis** [turbodiesel4598/NuclearCraft#120]
The alloy smelter machine can only accept the NuclearCraft item graphite dust to make steel.

The problem is in clients with many mods, using the NuclearCraft method of obtaining graphite dust can end up yielding a non-NuclearCraft oredict variant of dustGraphite, such as Graphite dust from Extreme Reactors.

I am simply requesting that you add the functionality of accepting any oredict variant of graphite dust. If this is a problem with other items, please make that obey the ore dictionary too.

**Comment by turnerlewis** [comment]
Another example I forgot to mention is Yellorium from Extreme Reactors. Functionally it is identical to uranium according to the oredict.

**Comment by turbodiesel4598** [comment]
The alloy furnace should not be accepting graphite dust of any kind - it should only take in graphite ingots - if it is accepting the dust, then that is a bug.

I can't think of any mods that add the dust and not the ingot off of the top of my head, but in case there are any, I'll added a graphite dust -> graphite ingot manufactory recipe :)

As for the yellorium issue - that's been there for a while, even back in 1.7.10. The problem arises because Big/Extreme Reactors adds yellorium to both the 'ingotUranium' and 'ingotYellorium'.

**Comment by turbodiesel4598** [comment]
Recipe added for 2.3
