### ISSUE TITLE
Console spam Basic solar panel

### ISSUE THREAD

**Issue by Nullga** [turbodiesel4598/NuclearCraft#122]
I just noticed today there console spam by basic solar panel but not all the time. Couldn't figure out what's triggering.

NC: NuclearCraft-2.2d--1.10.2
IC2: industrialcraft-2-2.6.234-ex110
Forge: 12.18.3.2316

[20:39:45] [Server thread/WARN] [IC2.EnergyNet]: Tile nc.tile.generator.SolarPanels$SolarPanelBasic@2a80c6b4 (dim 0: -754/67/-1086) was attempted to be queued twice for addition.

Thank you.

**Comment by turbodiesel4598** [comment]
The "attempted to be queued twice for addition" spam has been removed in version 2.3 - it was caused by me not checking if a tile had already been added to the E-Net. However, there is still spam from the IC2 E-Net in other forms when the block updates (become active/inactive), because there is no way that I can find to avoid it. Other mods like Mekanism has the same problem.
