### ISSUE TITLE
Feature Request: Report what's invalid about the casing

### ISSUE THREAD

**Issue by sandalle** [turbodiesel4598/NuclearCraft#136]
Based on https://github.com/turbodiesel4598/NuclearCraft/issues/135 , it would be nice if the UI reported _what_ is wrong with the reactor for it to be valid. :)

e.g. in [Big Reactors](https://minecraft.curseforge.com/projects/big-reactors), right-clicking on the multi-block with an empty hand will output the <x,y,z> of which block(s) are missing/invalid for the multi-block to form.

**Comment by turbodiesel4598** [comment]
I'll look into it. I don't think that should be too much trouble.

**Comment by turbodiesel4598** [comment]
Well, it was a little bit of trouble, but I've added this functionality partially. Due to the nature of the structure checks, the precise position of the missing/misplaced block will not be found everytime, but if it can be, then you will be told in the controller GUI.

Luckily, usually the controller will be able to tell you the position when the structure is close to complete, which is obviously when it's easiest to miss something. Hopefully a mistake or incompleteness should be reasonably apparent otherwise.

**Comment by sandalle** [comment]
Awesome, thank you _very_ much, @turbodiesel4598 ! I'm loving NuclearCraft so far.
