### ISSUE TITLE
Fluid output options - toggle tank production and running when full

### ISSUE THREAD

**Issue by TvL2386** [turbodiesel4598/NuclearCraft#146]
Hey Turbodiesel,

I love playing with your mod and gotten to the stage where I need more power. 
I've been watching your youtube video on the Electrolyser but I can't get the 4 liquids into 4 external tanks.

I seem to only be able to output the Hydrogen out of it. I'm piping it into a Mekanism tank.

Alrighty, never mind the above... Got it working after a bit of a hassle.
First I got the Hydrogen in the Mekanism tank and then I connected a first EnderIO Tank. I used the Mekanism tank to whitelist (in the EnderIO Ender Fluid Conduit) the Hydrogen to go to the first EIO Tank. Then I blacklisted Hydrogen for the second EIO Tank so I got Deuterium. Then I removed the EIO Tank with Deuterium and used it to blacklist  both Hydrogen and Deuterium for the third tank (etcetera....)

But, now the Electrolyser stopped working, because it cannot output Hydrogen anymore, the tanks (internal and external) are full... Might be a good option to implement "dump excess liquids" for the 4 internal tanks? Like the Mekanism Electrolytic Separator.

Love your mod!

Kind regards,
TvL2386

**Comment by TvL2386** [comment]
I've connected the Electrolyser to a Refined Storage Importer. I got 4x 64k Fluid Storage Blocks and whitelisted the fluids the Electrolyser creates.

The Refined Storage Fluid Storage Blocks have an option to void excess fluids. 
This is a bit better, however: I want to use Tritium and Deuterium for the Fusion Reactor (I think this is the fuel for it) and want to use the Oxygen for the Fluid Infuser.

I have no idea how fast I'm gonna burn through the fluids and I want to make sure I don't run out of one of them.

It would be cool if the Electrolyser would keep running until all fluids are full and just void all excess fluids until all tanks are full.

**Comment by TvL2386** [comment]
Hmmmm... If I pull water or lava out of my Refined Storage Fluid Grid, RS will fill an empty bucket in the system with the fluid, however the Nuclearcraft fuels can't be put in a bucket so it seems... Couldn't get a bucket either from the EIO tanks.

It seems I need to keep my tanks for whitelisting them on importers and exporters.

**Comment by turbodiesel4598** [comment]
> Might be a good option to implement "dump excess liquids" for the 4 internal tanks?

Should be simple to add :)
> It would be cool if the Electrolyser would keep running until all fluids are full and just void all excess fluids until all tanks are full.

I could add a button to the GUIs of fluid-producing machines that toggles that mechanic on and off - as you can probably imagine, there are some cases where you would not want that to happen.
> the Nuclearcraft fuels can't be put in a bucket so it seems... Couldn't get a bucket either from the EIO tanks.

That's really weird - they should be able to be put into buckets - just put some NC fluid on the floor and you should be able to bucket it up...
[And I just tested using a bucket in an EIO tank of helium - seemed to work.](https://prnt.sc/gui31j)

**Comment by TvL2386** [comment]
I'm playing All The Mods modpack with Nuclearcraft 2.3

![image](https://user-images.githubusercontent.com/459167/31320734-fa269ae4-ac79-11e7-890c-92bd84ac4439.png)

Doesn't want to put Oxygen in a bucket unfortunately.

The option to void until all 4 tanks are full are pretty good I think. I think the Fusion Reactor should have it too... why stop when the output is full, just vent it :)

Offtopic probably, but I'm trying to setup the Fusion Reactor. The size 4 which results in 11x11.
I'm really struggling with determining what fuel goes in there. I am generating Deuterium and Tritium with the Electrolyser but it's way too slow to generate enough for it to keep running...
How are we supposed to work with the fusion reactor in a survival world?

**Comment by TvL2386** [comment]
This is what I'm trying to do:
![image](https://user-images.githubusercontent.com/459167/31321100-518c8b44-ac80-11e7-8262-0e52ab59b9f8.png)

The idea is that I have all the liquids in my system, whether by hooking up 4 tanks with external storage or importing it into the RS network. I was thinking of exporting Deuterium and Tritium to a Fusion Reactor, however I can't produce it fast enough to keep the fusion reactor running

**Comment by turbodiesel4598** [comment]
> Doesn't want to put Oxygen in a bucket unfortunately.

The issue is that that isn't NC Oxygen. [NC Oxygen is blue and gaseous](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/resources/assets/nuclearcraft/textures/blocks/fluids/oxygen.png) - you must have another mod that adds Oxygen that _can't_ be bucketed.
> why stop when the output is full, just vent it

Because there are some machines like the melter that you don't want to void the outputs of. You don't want to just waste precious beryllium by accident.
> I am generating Deuterium and Tritium with the Electrolyser but it's way too slow to generate enough for it to keep running...

You're producing tritium from the electrolyser? [It should only be producing hydrogen and deuterium](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/ElectrolyserRecipes.java#L19)... or [perhaps you're using heavy water from Mekanism?](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/ElectrolyserRecipes.java#L23)
> it's way too slow to generate enough for it to keep running... How are we supposed to work with the fusion reactor in a survival world?

Similarly to the fission reactors, you should have more than one fusion reactor - you need multiple. Ill take you through roughly what I do, [and I'll use this page as a reference to recipes.](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/generator/FusionRecipes.java)

The way I do it is start with a Hydrogen-Hydrogen reactor that produces Deuterium. Then I combine the extra Deuterium produced by the electrolyser with that produced in the reaction and then set up a Hydrogen-Deuterium reaction that produces Helium3, which is a very powerful fusion fuel.

From then, there are lots of options, depending on what you want. You could do Hydrogen-Helium3 or Helium3-Helium3 reactions if you want to produce a lot of Helium4, you could try Deuterium-Deuterium reactions to produce Tritium, Helium3 and some Neutrons, and there are other options too.

You can use the Neutrons you generate to irradiate Helium3, Lithium6 or Boron10 to produce more Tritium, and use that in the famous Deuterium-Tritium reaction.

You could also use molten Lithium6, Lithium7 or Boron11 as fusion fuel. The Hydrogen-Boron11 reaction is quite slow, but probably the most efficient reaction known. Deuterium-Lithium7 and Helium3-Lithium7 are also powerful reactions, so those are also options.

Hopefully that gives you an idea of how the fusion system in the mod is set up :)

**Comment by TvL2386** [comment]
Hey Turbodiesel,

Thanks for your extensive reply! I'll definitely check out the Fusion reactor mechanics!
Very informing! 

When looking at the liquids the electrolyser is producing, I think they are the ones from Mekanism.
As you can see in the previous screenshot, I'm using your infinite water gen. block to feed the electrolyser.
![image](https://user-images.githubusercontent.com/459167/31328575-3741d63a-acd6-11e7-8347-96eff2c32764.png)

It seems to be a mod issue then.

**Comment by turbodiesel4598** [comment]
Ah, I see, you're using an old version of NC. In newer versions, the electrolyser doesn't produce tritium.
