### ISSUE TITLE
[Issues/enhancements] Electric machines Speed/Power Upgrades in general

### ISSUE THREAD

**Issue by Sharkking** [turbodiesel4598/NuclearCraft#15]
1) The Crusher produces Gravel when Putting Cobble, shouldn´t this be Sand or is this the default behavior ?

2) It is possible to place Speed upgrades into the Energy Upgrade slots of the machines (tested with electrical furnace and crusher). This should be blocked. 

3) since the Upgrades are crafted in a 3x3 field please allow them to be crafted at every workbench (thus to be able to programm them in AE2)

4) When a machine gets too less power (eg 8 speed upgrades without energy upgrade) the gui starts flickering (tested on electric crusher and Furnace)

kind regards keep up the good work

**Comment by turbodiesel4598** [comment]
1. Yes, this is intended - the gravel can then be crushed to sand.
2. I will see what I can do.
3. Seems reasonable - sure thing ;)
4. That's simply because the machine is running out of power after a single tick - there's not much I can do about that, really - speed and energy upgrades are going to change in the future, however.
Thanks for the feedback :)

**Comment by turbodiesel4598** [comment]
2. Still haven't got round to
3. Done
4. Fixed - just a small error in the checking of the energy available

**Comment by turbodiesel4598** [comment]
Speed and energy upgrades now increase the speed and efficiency, respectively, exponentially with each additional upgrade. For example, 1 speed upgrade reduces the process time by a factor 1.8, 2 reduces it by 1.8^2, 3 by 1.8^3, etc
