### ISSUE TITLE
[1.6c] Crash when extracting Liquid Helium fluid

### ISSUE THREAD

**Issue by CerberusRCAF** [turbodiesel4598/NuclearCraft#16]
Running NuclearCraft through its paces to test inclusion with my group's modpack, and had this crash.

Ran a Thermal Expansion Fluiduct from Liquid He Extractor, with Resonant Servo to pull fluid.  Crash occurred immediately upon activating the servo; I'd guess from trying to introduce the fluid "into the world."

http://pastebin.ca/3373126

**Comment by turbodiesel4598** [comment]
Strange... I do not see any mention of Liquid Helium in that report, or NuclearCraft...
I would have to guess I've done something wrong, but I would try to get into touch with KingLemming or someone who knows TE/fluids well. They may be able to tell you what's wrong.

**Comment by KingLemming** [comment]
The issue is that your fluid has a viscosity of 0. It's a Fluid system, not a SuperFluid system - it wasn't designed for that and you shouldn't be too surprised when things break as a result. ;)

Yes, liquid helium in a carefully controlled environment at a certain temp will behave as with viscosity 0. Liquid helium *in general* as it flows through a network of pipes will not. Give it something in the range of 1-5 and it'll be a fair approximation.

**Comment by turbodiesel4598** [comment]
Ah, right. Thank you - an easy fix for the next version ;)

**Comment by turbodiesel4598** [comment]
Done
