### ISSUE TITLE
[Request] Support multiple reactor ports

### ISSUE THREAD

**Issue by xenoflot** [turbodiesel4598/NuclearCraft#163]
RFTools cells cap at 20KRF/t and TE's at 25KRF/t. When you're running multiple quarries that will happily draw that much each, it would be nice if the reactors would support multiple IO ports.

Forge 14.23.0.2512
NC 2.5a
MC 1.12.2

Cheers!

**Comment by turbodiesel4598** [comment]
You should be able to use as many reactors ports as you like in the fission structure... unless there's a bug I'm unaware of?

**Comment by xenoflot** [comment]
Tested some more just now by putting 4 ports onto the reactor and clipping a TE resonant cell onto each. What seems to be happening is that the reactor is only feeding a single port at a time. That is, connect 4 partially-filled cells and it'll fill them one at a time.

**Comment by turbodiesel4598** [comment]
The reason I imagine this happens is because the ports _pull_ from the controller - the controller doesn't _push_ to the ports... I'm not really sure how to do away with the effect of this, but is it a big problem anyway?

**Comment by trevorjd** [comment]
IMO it's something to have on the to-do list. I can quickly think of two use cases where the current method is problematic.

1. In the case that you have RF cables that don't support the reactor's full output, you'll need multiple power taps and multiple power lines to take the output to your storage. (This is how I discovered the issue. I hadn't yet researched fast RF cables!)

2. In the case that you have a quarry, you might want to use a second power tap so that you know the quarry isn't going to suck all the energy from the reactor, leaving none for your base.

**Comment by turbodiesel4598** [comment]
Ok - I'll just have to spend some time thinking how best to do this - I guess for now if you have any form of energy storage block that can have its output limited to some number then you can manually redirect power that way.

**Comment by turbodiesel4598** [comment]
Sorted! Will be a new mechanic in the next version :)
