### ISSUE TITLE
Electrolyzer doesn't work 

### ISSUE THREAD

**Issue by MelanX** [turbodiesel4598/NuclearCraft#167]
I'm playing in the latest version and the Electrolyzer has water and energy but doesn't work. 
I really need Oxide stuff.
Maybe there is a way to implement Mekanism support, too? Would be very nice, because I really need that in Modern Skyblock 2.

**Comment by xenoflot** [comment]
Hi MelanX,

The "latest version" can change between when you post and when folks are reading your report. Please specifically mention which version you're running. It's also essential to mention which version of Minecraft Forge you're running. You get get this info easily in-game by hitting ESC then Mod Options. Forge should be the 4th on the list, and you can search NuclearCraft using the box at the bottom.

One suggestion, make sure that you're disposing of the gasses that you don't need. The NuclearCraft electrolyzer will produce Hydrogen & Deuterium in addition to Oxygen. You need to pipe these to a Nullifier so that the electrolyzer can keep producing oxygen. Thermal Expansion ducts and XNet can be used to pull these gases out of the electrolyzer but you'll need to use some filters to get it all right.
