### ISSUE TITLE
[1.10] Fission reactor crashes when inserting/removing custom added fuel

### ISSUE THREAD

**Issue by vishtheshnu** [turbodiesel4598/NuclearCraft#195]
I set up a single control cell reactor and used crafttweaker to add an IC2 uranium fuel cell as fuel. When using the mouse wheel to add and remove items from the controller's inventory slot (mousetweaks was installed), the game crashed with the following error: https://pastebin.com/BwXe4Aus

Specifically, it crashed when I tried to move the mousewheel in the direction to remove items from the controller.

**Comment by turbodiesel4598** [comment]
A few possibilities here - could I see your recipe addition in the script?

**Comment by BrisingrAerowing** [comment]
FWIW, I used to get crashes like this in 1.10.2 with MouseTweaks on a lot of inventories that had specific slots for things. It seems to be a bit more stable in 1.12.2.

**Comment by turbodiesel4598** [comment]
I have done quite a bit of testing with this now, and there doesn't seem to be any way to cause a crash like this other than through Inv Tweaks - what I think is happening is that Inv Tweaks is pulling from the hidden input slot that the fuel sits in while it is being used up, rather than the actual output slot.

**Comment by vishtheshnu** [comment]
Yeah, I'm pretty sure that's what it is. I had inv tweaks installed.
