### ISSUE TITLE
Sulfur problem:pull request

### ISSUE THREAD

**Issue by MadRatSRP** [turbodiesel4598/NuclearCraft#201]
Please, add your sulfur to the ore dictionary. I have both of them, one is yours and one from the thermal foundation.

**Comment by turbodiesel4598** [comment]
I'm gonna guess you were trying to build DU plates or crystal binder. The issue is not that NC's sulfur isn't added to the ore dict, it's that sulfur is not actually the ingredient that goes there - it's a different ore dict entry that sulfur is added to, but other sulfurs won't be added to it. I've fixed this by changing the recipes a little bit - it'll be in the next update :)
