### ISSUE TITLE
energy upgrades 

### ISSUE THREAD

**Issue by minecrafterseppe** [turbodiesel4598/NuclearCraft#202]
question why are there no energy upgrades ?  i can see speed upgrades but i cannont see energy upgrades

**Comment by turbodiesel4598** [comment]
The reason is, well, because there are none! I suppose you are wondering why there is a second upgrade slot in machines... if so, then yes, you would be right to wonder where the upgrades for those are - the answer is that they just haven't been added in yet. All I am sure of so far is that I want each machine to have a second, unique upgrade :)
