### ISSUE TITLE
MineTweaker Manufactory: Not removing recipes from JEI (1.10.2)

### ISSUE THREAD

**Issue by CJMinecraft01** [turbodiesel4598/NuclearCraft#222]
So I've been trying to remove the recipe for graphite dust from the manufactory. I've been following the guide created and my ZenScript is as follows:
```
# Imports
import mods.nuclearcraft.manufactory;

# Globals
val graphiteIngot = <nuclearcraft:ingot:8>;

# Graphite Creation

# Remove the recipe to get graphite by smelting coal
furnace.remove(<ore:ingotGraphite>, <minecraft:coal:*>);

# Remove the recipe to get graphite dust by manufactoring coal
manufactory.removeRecipe(<bigreactors:dustmetals:2>);
```
Every time I reload minetweaker using `/mt reload` it adds the recipes for graphite dust again (in JEI) and I now have about 3 pages of graphite dust recipes which all take iron as an input.

Fortunately the recipes are removed just it doesn't update in JEI

If you need any more information, just let me know.
Thanks in advance

**Comment by turbodiesel4598** [comment]
The first problem is that you need to use `mods.nuclearcraft.manufactory.addRecipe` rather than just 
`manufactory.addRecipe`, but that doesn't fix the issue totally.
What's happening, as far as I can tell from testing, is that only one of the Manufactory recipes for graphite dust is being removed by the command. As soon as you remove the recipe again in the script, both recipes are removed and it is no longer possible to make it.
It's not really a 'bug' that only one of the recipes gets removed, but it's not an intended feature either, so I'll get that fixed up as soon as I can.
As for the recipe getting added over and over in JEI... there's nothing that can really be done about this, and the maker of CraftTweaker has said that it happens simply because of the way JEI stores recipes.

**Comment by CJMinecraft01** [comment]
Regarding the first suggestion, I imported the package and I am simply referencing it to that (the same way you do in java) so this shouldn't theoretically effect it. I also tried running the remove recipe in a loop in the file and it came up with an error saying it can't find a recipe with the output of graphed suggesting the recipe was removed. It was removed entirely from the block but not JEI. I am using MineTweaker and not CraftTweaker I belive as some features on the CraftTweaker wiki are not available. Thanks for the fast response and for looking into this. If you need any more information, please do let me know. Thanks

**Comment by turbodiesel4598** [comment]
No problem man :)
Ah, so if I understand you correctly, the recipe is actually being removed (i.e. it can no longer be made), but not from JEI?

**Comment by CJMinecraft01** [comment]
Yes that is correct.

**Comment by turbodiesel4598** [comment]
And is this true even if `/mt reload` isn't used (i.e. if the script is ran as the game starts up)?

**Comment by CJMinecraft01** [comment]
Yes. I've just restarted the game, although there are now no extra tabs, and extra recipes in JEI, the recipe still shows but in the block it doesn't work

**Comment by turbodiesel4598** [comment]
It's a peculiar one. It seems to only happen in versions 1.10.2 and 1.11.2, before the change to the way recipes are registered. I'm not sure there is a solution to this on my side, since, as far as the mod is concerned, the recipes are actually being removed correctly. For some reason JEI is hanging on to them...

**Comment by CJMinecraft01** [comment]
Thanks for looking into this, I'll try to contact Mezz and see if he can help me. I'll leave the issue open (unless you think otherwise)

**Comment by turbodiesel4598** [comment]
I’ll see if I can talk to him too - might as well leave it open in case there turns out to be something I should do.

**Comment by CJMinecraft01** [comment]
So far I have not had a response, do you reckon I should just continue to wait?

**Comment by turbodiesel4598** [comment]
Yeh, might as well - might just be a little bit busy... he's got a lot going on :)

**Comment by turbodiesel4598** [comment]
Well, I'm only four months late, but I think I fixed the problem... if you do happen to still be looking for the solution to this, I'll get a new build out tonight. If not... well, at least I can put this issue to bed ;)
