### ISSUE TITLE
[Question] Ores

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#252]
Heya! 
Have you recently moved the initialization of NuclearCraft ores to postInit? I'm no longer able to set their Harvest Level with the mod Tool Progression, but I have previously been able to.

NuclearCraft-2.9d--1.12.2

**Comment by turbodiesel4598** [comment]
Hola! No, I have not, so that is a bit bizarre...

**Comment by NillerMedDild** [comment]
Alright, thanks.

**Comment by NillerMedDild** [comment]
I was told by the dev of Tool Progression that you are currently overriding the method `public int getHarvestLevel(IBlockState state)` without also overriding the corresponding `setHarvestLevel` appropriately, doing so should fix it.

**Comment by turbodiesel4598** [comment]
Okay, hopefully should be sorted for the next verison - I'll leave this open until it's definitely fixed.

**Comment by turbodiesel4598** [comment]
Did this issue get fixed?

**Comment by NillerMedDild** [comment]
No I'm afraid not :/

**Comment by turbodiesel4598** [comment]
Hmmm... don't know what the issue is then - I'm [setting the harvest levels](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/block/BlockMeta.java#L145-L151) and [getting the same harvest levels](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/block/BlockMeta.java#L153-L157), so I don't actually know what I'm doing wrong...

To scoot around this issue, would a config option for the harvest levels of the ores do the trick?

**Comment by NillerMedDild** [comment]
That works for me :)

**Comment by turbodiesel4598** [comment]
Sorted :)
