### ISSUE TITLE
[Suggestion/Question] Make the time units in the config all the same

### ISSUE THREAD

**Issue by kerzenhans** [turbodiesel4598/NuclearCraft#254]
There are two values in the config who are not mesured in ticks but in seconds. The active cooler max rate and the decay generator production. 
I don't know if it's just me, but I see this as an inconsistency in a user interface. Which in my case took me quite some time to utilize active coolers work. Because I had to juggle 3 values with diffferent scales.

Now to the questin:
I left an reactor with positive heat without redstone signal. Nonetheless it consumed all my liquid glowstone (20k buckets). Shouldn't there be a check to only use liquid when the reactor is actually generating?

**Comment by turbodiesel4598** [comment]
The reason that I use both ticks and seconds in the configs and tooltips is unfortunately because I have two options, and I went for that one. The other option is everything in units of seconds, as some of the 'rates' are smaller than 1 RF or mB per tick. I didn't go for that because it would just make a lot of the numbers using ticks a lot clumsier - suddenly common things like cooling rates become more annoying to calculate because you'd have to convert the units.

As for your bug, that is an oversight on my part... is fixed now though!
