### ISSUE TITLE
CraftTweaker - Electrolyzer

### ISSUE THREAD

**Issue by NillerMedDild** [turbodiesel4598/NuclearCraft#269]
Hey! I'm having a hard time removing recipes from the Electrolyzer with CraftTweaker, could you help me in the right direction? I'm attempting to remove Deuterium recipes with the following script:
`	mods.nuclearcraft.electrolyser.removeRecipe(<liquid:deuterium> * 475,  <liquid:deuterium> * 475, <liquid:oxygen> * 500, <liquid:tritium> * 50);
	mods.nuclearcraft.electrolyser.removeRecipe(<liquid:hydrogen> * 475,  <liquid:hydrogen> * 475, <liquid:deuterium> * 50, <liquid:oxygen> * 500);
`
and on reboot, the game tells me it cannot find the items. I have however used the same names to succesfully add recipes to the Electrolyzer. Maybe the `removeRecipe` is bugged?

Minecraft 1.12.2
NuclearCraft-2.9e--1.12.2

**Comment by turbodiesel4598** [comment]
Seems like it is - thanks for pointing that out. Will work on a fix :)

**Comment by turbodiesel4598** [comment]
Okay, should be fixed now for the next version, and that should be out very soon. Will also add the option to remove recipes using the inputs rather than outputs so removing Electrolyser recipes should be a little easier :)

^ The above will mean the lexicon will change a bit, from "removeRecipe" to "removeRecipeFromInputs" and "removeRecipeFromOutputs".

**Comment by NillerMedDild** [comment]
Sounds great, thank you!
