### ISSUE TITLE
Active coolers not considered "active" for dependent blocks

### ISSUE THREAD

**Issue by RobertBouillon** [turbodiesel4598/NuclearCraft#284]
If a gold cooler requires redstone and water, it will work adjacent to passive redstone and water blocks. Replace either redstone or water with an active cooler, and the gold cooler no longer activates.

I'm using 2.9e on 1.12.2 (FTB Revelation Pack v1.8).

**Comment by turbodiesel4598** [comment]
This is by design - active coolers are designed to be powerful, but since they are so effective, they have to have drawbacks - this is one of them ;)

**Comment by RobertBouillon** [comment]
Okay cool. Thanks :)

**Comment by Thalzamar** [comment]
please add this to the wiki, the nc planer tool shows it opposite of what you just said and i couldn't find anywhere written that it behaved like this
only found this by accident since i thought it was a bug and wanted to report it here

**Comment by turbodiesel4598** [comment]
If that's true you may want to get in touch with Hellrage, the dev of the planner. You can find them [on GitHub](https://github.com/hellrage/NC-Reactor-Planner) or through our [Discord server](https://discord.gg/KCPYgWw) :)

**Comment by Thalzamar** [comment]
yeah i was pretty miffed when my reactor had only 60k colling instead of the 90k cooling the planer said it should have , first thought active cooler not working but after checking they where so 

recorded it on github, don't have discord 
still thanks for the great mod and the best things are the tooltip, still hope someday there will be more passive coolers for an even bigger puzzle (headache)

**Comment by turbodiesel4598** [comment]
I believe they're on it now. Thanks very much! And yes, your hope is certainly coming true in the future when the mod undergoes major changes ;)
