### ISSUE TITLE
Mod interaction issue with LittleTiles

### ISSUE THREAD

**Issue by GuntherDW** [turbodiesel4598/NuclearCraft#294]
As discussed in Discord, when LittleTiles is installed multiblocks such as the fusion reactor are broken.
Old magnets before the mod was installed (or between reinstalls) are fine, but newly placed magnets will refuse to turn on.

This causes the fusion reactor to not want to start up because it thinks the electromagnets are non powered.

![screenshot](https://i.imgur.com/pVIE0SM.png)

I'm not sure which mod is to blame yet, so I'm posting this on both issue trackers and linking between said issues.

Versions:

- Minecraft: 1.12.2
- Forge : 14.23.3.2669
- LittleTiles : 1.5.0-pre97_mc1.12.2
- NuclearCraft : 2.10j

LittleTiles issue : https://github.com/CreativeMD/LittleTiles/issues/85

**Comment by CreativeMD** [comment]
That's a weird issue and I have no idea why LittleTiles could cause something like this. I suspect it's one of the asm transformations I do, so here is a small list of things I do:

**Universal**
- Remove message size limit in `NettyCompressionDecoder`
- Remove nbttagcompound size limit in `PacketBuffer`
- Add check for different `AxisAlignedBB` class in `AxisAligned.intersects()`
- Add `calculateYOffsetStepUp(AxisAlignedBB,AxisAlignedBB,double)` to `AxisAlignedBB`
- Redirect `ForgeHooks.isLivingOnLadder()` to my own method
- Change one call of `AxisAlignedBB.calculateYOffset()` in `Entity.move()` to `AxisAlignedBB.calculateYOffsetStepUp()`

**Client**
- Add method call in `Minecraft.middleClickMouse()`
- Add method `shouldUpdate()` to `ITickable`
- And If-case to `World.addTileEntity()` so it will only add a tileentity to the ticking list, if `ITickable.shouldUpdate()` returns true
- Remove all tileentities which should not tick (due to `ITickable.shouldUpdate()` returning false) from the ticking list

**Rendering**
- hook into `RenderGlobal.loadRenderers()` and change `new ChunkRenderDispatcher()` to `new LittleChunkDispatcher()`
- Add field `LittleStructure littleBed` to EntityPlayer
- Redirect `EntityPlayer.getBedOrientationInDegress()` to my own method.
- Add a call to one of methods in `ForgeHooksClient.orientBadCamera()`
- Redirect `RenderChunk.resortTransparency()` to my own method
- Change some more stuff in rendering a `RenderChunk`
- Add field `boolean littleTilesAdded` to `BufferBuilder` class
- Set `littleTilesAdded` to false in `BufferBuilder.reset()`

So maybe you have an idea of what is causing this issue?

**Comment by SonarSonic** [comment]
I imagine it's a clash between your `ITickable.shouldUpdate()` and [TilePassiveAbstract.shouldUpdate()](https://github.com/turbodiesel4598/NuclearCraft/blob/c3cc7d061ca985d00cabed9663e4432e205938d4/src/main/java/nc/tile/passive/TilePassiveAbstract.java#L116) in NuclearCraft. 

@CreativeMD I don't know why your adding the method, but I think you should rename to something very specific and unlikely to clash like `ITickable.shouldLittleTilesUpdate() ` as i imagine `shouldUpdate()` is a method added to a large number of tiles in various mods.

**Comment by CreativeMD** [comment]
Oh right ... damn completely forgot about that ... it will be fixed in the next pre-release (don't know when it will be there).

**Comment by turbodiesel4598** [comment]
Awesome - cheers!
