### ISSUE TITLE
Some fluids (like Molten Diamond) not showing texture when placed in world

### ISSUE THREAD

**Issue by Emerald-Chicken** [turbodiesel4598/NuclearCraft#308]
A couple of fluids, like molten diamond, seem to be fine when viewing in JEI. However, once placing the fluids in world, they show the purple/black block no texture. Both for the still and flowing forms.

**Comment by turbodiesel4598** [comment]
This is probably because you have not enabled the blocks corresponding to the fission-related fluids in the configs - they are disabled by default as they take up a huge number of block IDs, and so big packs crash if it's enabled. In 1.13, block IDs are totally gone and so there will no longer be a limit on the total number of blocks that can be registered to the game, so then I'll just register them all as usual :)
