### ISSUE TITLE
Decay Generator turning to Thorium/Uranium blocks to lead 

### ISSUE THREAD

**Issue by ShaneCourtrille** [turbodiesel4598/NuclearCraft#331]
I have a question around the Decay Generator.  I'm playing with the 'All The Mods 3' pack and I setup a decay generator with 1 block of ic2 uranium on one side and a thorium block on another side.  Within 5-10 seconds the uranium became a Lead block and maybe another 10-20 seconds later the Thorium became a Lead block.  I seemed to be getting way more power then I expected from it BUT I can't find anything to indicate things should have become Lead blocks.

So with all that said.. is the lead block thing normal? what about the timing? I found another issue posted about the timing config being in ticks vs seconds so maybe its a config issue?

Here is the config if that helps...

```
# RF/s generated by adjacent radioactive blocks. Order: Thorium, Uranium, Depleted Thorium, Depleted Uranium, Depleted Neptunium, Depleted Plutonium, Depleted Americium, Depleted Curium, Depleted Berkelium, Depleted Californium.
    I:decay_power <
        80
        80
        10
        10
        10
        10
        20
        20
        25
        40
     >
    I:generator_rf_per_eu=16
    I:generator_update_rate=20
```

Thanks!

**Comment by turbodiesel4598** [comment]
Hey there! First off, there is a bug (fixed for next version) which causes the power and decay speeds to be much larger than they should be (20 times too quick), which is why they decayed so fast and generated more power than you'd usually expect. I am also going to increase the lifetimes as they are a bit too short.

You can check the recipes in JEI, but the decay chains follow the real paths, skipping isotopes that are not actually in the mod.

Hope that helps!
