### ISSUE TITLE
Client crashes with latest EnderIO version.

### ISSUE THREAD

**Issue by Bulldog83** [turbodiesel4598/NuclearCraft#333]
Game crashes when I try to righ-click on EnderIO's machines in JEI, to see their recipes.

Reference to EnderIO's github:
https://github.com/SleepyTrousers/EnderIO/issues/4744

Crash-report:
https://gist.github.com/Bulldog83/7ec41d98060822c8ac983a0022430ae4

Some quote from EnderIO's discord:
> **HenryLoenwind**: because before it would just silently crash in the background, and not so silently at other locations. This is one of the crashes that prevented the tank gui from opening

Minecraft: 1.12.2
Forge: 14.23.4.2705
NuclearCraft: 2.10p

**Comment by turbodiesel4598** [comment]
Hey there - sorry about this. The way to fix this should be to head into the NC configs and enable the addition of fluid blocks to the game.

They are disabled by default because I had issues reported related to running out of block IDs, as NC adds hundreds of fluids which can send big packs over the limit.

The crash before was different - I just screwed up the registering of fluids, so it was a mistake on my part. Here, unless we’ve just been lucky (as EIO and NC have been in packs together without a crash like this for some time now), it seems EnderIO more recently added some new method that at some point looks at the contents of fluid containers, and getting the block returns null and crashes.

**Comment by HenryLoenwind** [comment]
You know that you can create a fluid without a block?

**Comment by turbodiesel4598** [comment]
Yeh, think I just found how - set the `block` in the fluid to null?

**Comment by HenryLoenwind** [comment]
Or just not create the block object.

**Comment by turbodiesel4598** [comment]
Yes true - sorry, I'm a little discombobulated by my own way of registering the fluids and their blocks, but it should be fine now.

**Comment by Pythonic-Rainbow** [comment]
I am from EnderIO#4763 , posted this comment to follow it

**Comment by Pythonic-Rainbow** [comment]
how do I update the config? I mean which line in the NC.cfg?

**Comment by Pythonic-Rainbow** [comment]
So I've updated the config , but this causes another crash
https://cdn.discordapp.com/attachments/467712602189987840/467815114108829709/unknown.png

**Comment by turbodiesel4598** [comment]
Fixed in the upcoming v2.11 :)
