### ISSUE TITLE
[CraftTweaker] Electrolyser removal, 3 outputs

### ISSUE THREAD

**Issue by Discomanco** [turbodiesel4598/NuclearCraft#345]
In the later versions of NC, it is no longer always the case that it will output 4 fluids.
What used to be `Hydrogen*475, Hydrogen*475, Deuterium*50, Oxygen*500` is now `Hydrogen*950, Deuterium*50, Oxygen*500, Nothing`.
CraftTweaker can't seem to support that, as it wants 4 outputs to see it as valid

Script
`	mods.nuclearcraft.electrolyser.removeRecipeWithOutput(<liquid:deuterium> * 950, <liquid:oxygen> * 500, <liquid:tritium> * 50);
	mods.nuclearcraft.electrolyser.removeRecipeWithOutput(<liquid:hydrogen> * 950, <liquid:deuterium> * 50, <liquid:oxygen> * 500);`

NC 2.11
CraftTweaker 4.1.9

**Comment by NillerMedDild** [comment]
Adding null as the 4th output does not work either unfortunately.

**Comment by turbodiesel4598** [comment]
Just tested and it does work - you need to add an additional set of brackets, so that your script looks something like `([...])`, otherwise CT will not read the recipe correctly.

You're looking for something like this:

`mods.nuclearcraft.electrolyser.removeRecipeWithOutput([<liquid:hydrogen>*950, <liquid:deuterium>*50, <liquid:oxygen>*500, null]);`

You may want to check out the [updated CT document](https://github.com/turbodiesel4598/NuclearCraft/blob/master/craftTweaker.txt) for more info :)

**Comment by NillerMedDild** [comment]
Woops, I only checked out the Electrolyser section in the updated document ^^' Thanks!

**Comment by turbodiesel4598** [comment]
No prob!
