### ISSUE TITLE
[Question] Powering Fusion Electromagnets

### ISSUE THREAD

**Issue by scotty9090** [turbodiesel4598/NuclearCraft#365]
In your latest video, I thought I saw that power would spread across the fusion electro-magnets - i.e. power input is only needed on one magnet per ring.  That doesn't seem to be the case (I am on 2-11.g).

Is this a feature that hasn't been released yet, or did I misunderstand what I saw in the video?

**Comment by turbodiesel4598** [comment]
Hey there - sorry, I should have explained what happened in a bit more detail - I have a config option on called 'passive permeation', in the processors section. It is off by default, but if you turn it on ou'll get that energy spread :)

**Comment by scotty9090** [comment]
Fantastic, thank you!  Never would have found that on my own.

**Comment by EricBuist** [comment]
Hi,
These configuration options are really problematic. Modpacks configure them differently so that causes a lot of headache and pain. In Modern Skyblock 3, they probably left that by default so no power propagation between electromagnets. That makes active cooling pretty much impossible, at least using water. I am able to install 8 water coolers on the corners but not really more. There is no way to predict how other coolers will perform, except maybe, again, alt-tab out the game, search on Internet and go back in. Passive coolers indicate their rates, not active coolers. Yes I can change the config but then I have to wait, wait, and wait again to restart the pack, which takes more than 10 minutes. Maybe I need to switch pack for something configured to be easier or at worst quicker to start so it would be less painful to tweak configuration as much as necessary.
