### ISSUE TITLE
[Suggestion] Combine decay generators and decay hasteners

### ISSUE THREAD

**Issue by xenon54xenon54** [turbodiesel4598/NuclearCraft#401]
Combine the decay generator and decay hastener, making a machine that can produce RF from decaying blocks adjacent to it and from items put inside. This could be implemented by making the decay hastener have the same block adjacency effects as the decay generator, slowing the processing time, and perhaps changing power output and process time based on the isotope's half-life. Existing UI animations could be reused.
So basically add the decay generator mechanics to the decay hastener (because that's just a neat idea and better for bulk operations), slow the processing time for balance, and maybe add in variable RF/tick and process time based on the isotope being processed (isotopes w/ longer half-lives are less energetic and decay more slowly, so DU would still not be very useful, but maybe isotopes with alpha decay vs beta decay have a higher yield?). And it would have to be cheap enough to be made without a manufactory, bc otherwise there would be the same catch 22 the decay generator was made to solve, and would also have to accept natural U and Th ingots/dust/blocks.
The decay hastener could also be renamed to the decay generator, and maybe get the same skin. Speed upgrades could be used at the expense of some of the base fuel energy, and it should still be too inefficient for it to be used as a substitute for a reactor.

**Comment by turbodiesel4598** [comment]
This is actually quite tricky to do with the way the mod is set up, especially since combining a generator and processor causes complications with energy transfer to/from the machine. I also just wonder whether or not this is 'necessary' - I've rarely seen the Decay Generator used at all anyways, and most players like to have machines in a compact, automated configuration which would not allow this merging to be utilised effectively.

**Comment by xenon54xenon54** [comment]
Clarification: it would only be a generator, not a processor and a generator. It would only produce energy from decaying isotopes.
I suggested this merge because the decay generator is not being used due to the difficulties in automating it and the limited recipes it has. This would fix both issues by 1) adding the recipes of the decay hastener and 2) allow for items to be used instead. It would also make more sense for decaying isotopes to produce energy rather than cost it.

**Comment by ASDFGHT0** [comment]
While decaying isotopes do release energy, it would probably take so much energy to accelerate their decay (if it's even physically possible at all...), that the result is a net consumption of energy rather than a net production of it.

**Comment by turbodiesel4598** [comment]
I see... so it would just be a normal machine, but a generator instead for decaying isotopes? As ASDFGHT0 says, the reason the hastener takes power is because the decay is being 'accelerated', while the generator is just producing power from the heat of the natural decay. The generator is there as a suggestion for a while back (I believe it is being used as an early-game crafting mechanic) rather than an obvious power genration option for most players.

**Comment by xenon54xenon54** [comment]
However, the decay generator still dramatically speeds up the rate of decay for blocks. A block of Th-230 will currently only decay if it is next to a decay generator. The only way to prevent the decay generator from being used as a super early, low cost, OP RTG analog is to make it burn through its fuel. The inconsistency right now is that the decay generator and hastener speed up decay, but the isotopes do not decay by themselves.
Currently, after making a decay generator to power a manufactory to make an RTG or solar panel, it is essentially thrown away, and never used again, because it is orders of magnitude more efficient to burn the fuel it uses in a reactor, which results in obsolescing power generators with no way to reuse them.
Combining decay generators and hasteners clears up the inconsistency of both using and producing energy with accelerating radioactive decay. It is currently possible to power a decay hastener that is decaying U-238 with decay generators that are also decaying U-238, and somehow still have balanced energy consumption/production, and also perform the decay faster than it naturally occurs. This is unrealistic, and therefore should be fixed. It's not at all a high priority issue, just something that should probably get done some time. It would require figuring out decay rates, net energy production of isotopes, flipping the machine to a generator, and modifying its recipe, but the first method of power generation could be repurposed after the first day and would no longer be a thermodynamic contradiction to another machine.

In response to ASDFGHT0, fission reactors _produce_ energy by accelerating the decay of fuel isotopes, and this acceleration is caused by a physically possible process, known as neutron-induced fission. The decay products are very different from what is obtained from natural decay, but the process is far faster, and much more energetic.

**Comment by turbodiesel4598** [comment]
I do understand where you're coming from, but I'm still not convinced that they need to be combined. I sort of like the crudeness of the decay generator - no GUI, placing blocks around it, etc, and cheap enough to be built before the manufactory. The decay hastener's 'role' is just fundamentally different. If we assume it does take a net amount of energy to speed up the decay of a radioactive isotope, then I don't see why the mechanics of the two machines is physically inconsistent.

However, I do think you're right that the different isotopes should have different recipe speeds in the hastener, a bit like how the different isotope blocks will decay in different times around the generator.

**Comment by turbodiesel4598** [comment]
Ok, a bit of progress on this idea - I suppose one way to avoid undoing what the decay generator was added for would be to still separate the hastener and generator, but change the 'decay hastener' into a 'decay chamber' and essentially just make it a version of the generator which accepts item stacks rather than needing to be surrounded by blocks? The reason this may make more sense in NC now is that in the future, spent fuel pools will be added to allow for decaying isotopes to heat up water.

**Comment by xenon54xenon54** [comment]
I agree. That also makes sense.

**Comment by turbodiesel4598** [comment]
I've come back to these earlier issues to see if I can clean any up, and it's been a while since I thought about this, but I have to say that, in hindsight, I still want the decay hastener to be an energy sink rather than an energy source. However, what has happened in the overhaul builds is that recipe times are now dependent on the radiation levels of the inputs :)

The 'spent fuel pool' will instead be a generalised 'decay pool', primarily used as a way to preheat water for efficient steam generation.

The decay generator is a bit of an anomaly, I agree, but as I mentioned above, it was added as a request for an early-game energy source, and I think there's really very little issue with having one generate energy and the other consume it.
