### ISSUE TITLE
Fluid extraction from input slots

### ISSUE THREAD

**Issue by SteamDoge9000** [turbodiesel4598/NuclearCraft#449]
Hello 

i Am unable to have any possable way to remove any of the liquid contents from a fluid mixer After puting it in to the machine and also being unable to remove it without wasting the resources via dump

I tried using ender I\o but it only seems to take fluids out after they are prosessed

This is a real pain espechaly if one person were to go though a lot of work to obtain the fluids needed to end up putting it into the wrong device and being UNABLE to get it back 

Please fix this,
i bet im not the only one that is bugged by this as well

**Comment by turbodiesel4598** [comment]
This will be fixed when machine sidedness is implemented ;)

**Comment by SteamDoge9000** [comment]
👌 
oh btw can you make it so the S'more S'mingot can be used in Tconstruct

Btw, using Culinary Construct, i made the Quitruple S'more s'mingot

**Comment by C4PTRAMPAGE** [comment]
> This will be fixed when machine sidedness is implemented ;)

...are you going to handle sidedness like galacticraft does (   :)   ) or more like the way mekanism does? (   :(   )

**Comment by turbodiesel4598** [comment]
I don't know how GC does it, but it will probably end up a lot like the system Tech Reborn uses, where each slot can be configured :)

**Comment by C4PTRAMPAGE** [comment]
with gc you have to use a wrench and shift right click to cycle through sides (excluding top and bottom) for the input (power only and only some machines, others have fixed input / output sides) in all honesty its a messy way of doing things but i sort of like it.

**Comment by C4PTRAMPAGE** [comment]
i guess what i like about it is its willing to set limits where your allowed some customization but not a huge amount so you still need to think about how to setup machine rooms efficiently.

**Comment by turbodiesel4598** [comment]
Well, mods have got to have different artistic styles to keep sets of mods having a richer flavour to them. And it seems, from the Discord server, most players using NC would like as configurable a system as possible, hence the Tech Reborn route.

**Comment by turbodiesel4598** [comment]
Added in 2.18 ;)

**Comment by greenking13** [comment]
Hello turbodiesel4598,

Apologies for messaging within an issue closed for nearly a year, but I assumed it would be better to discuss in a relevant issue rather than a new one. I'm using NC 2.18w and I am wondering how precisely one extracts mistaken fluids from, as an example, the chemical reactor's first input slot. I would assume it has to do with the side configuration, as seemingly discussed within this issue as well, yet from what I've tried so far, I am unable to extract. While the mistake I made isn't a majorly complicated issue and I could just void it, I'd be nice to understand how one would go about resolving this without resorting to voiding the liquid. (Which is what I assume "Shift Click to clear tank" means, and I doubt that feature does a check on if there's a connected tank to send rejected fluids to, although if it does, I'm going to feel a bit dumb for the assumption.)

Thank you for a response,
Green

**Comment by turbodiesel4598** [comment]
@greenking13 You should be able to set one of the tank's side configs to output mode, and then extract the fluid using some pipe/tube from that side. NC doesn't auto-output, so you'll need to actively extract the fluid :)

**Comment by greenking13** [comment]
That works if the fluid you're trying to get out is within the output slots, but from what I've seen of the side configs, you cannot pull from an input slot, which is what I was attempting to do, since I had mistakenly placed sulfur dioxide or something like that into the input by mistake when I was trying to extract it from the output.

**Comment by turbodiesel4598** [comment]
@greenking13 So you're not able to do [this](https://youtu.be/yjRUd7svh24?t=274)?

**Comment by greenking13** [comment]
Wow, I'm dumb. I'm sorry. I have no idea how I never clicked the side configuration more than once. I just assumed there was disabled and input for the input slots and disabled and output for the output slots.. Apologies and thank you very much!

**Comment by turbodiesel4598** [comment]
No worries!
