### ISSUE TITLE
[Suggestion] Synthesis of heavy isotopes in colliders

### ISSUE THREAD

**Issue by BlueCreeper160** [turbodiesel4598/NuclearCraft#470]
I think the atomic collider is cool to create new elements. (and synthetic isotopes) like Rutherfordium or Proactinium (Transneptunian elements) and uses for this elements.

And Why not residues from the fission or fusion reactor (uranium-235 + uranium-236 creates kripton-92 and 141 barium)

**Comment by turbodiesel4598** [comment]
I like the idea of generating the heavier fission isotopes through a system like this - effectively an endgame way to jump to the heavier, better fuels.
The main reason I don't want to go too far down the chain of heavy elements for use, say, in fission reactors is simply because eventually these elements become incredibly unstable, and that side of their nature is difficult to add to the game in a simple way, and I don't really want the radiation system to become too complex.

As for fission reactor waste products, the main reason these are not generated is simply because modded minecraft gives the players ways to deal with waste trivially, so there's not much point in my mind of devising a system for it. That's why fuels instead generate radiation while they run in reactors, which takes some effort to deal with.

But yes, I like the idea of building specialised colliders to generate heavy isotopes :)

**Comment by ASDFGHT0** [comment]
For the superheavy isotopes, the only ones that might be considered stable enough for use would be Es-252 (~472 day half life), Es-254 (~276 day half life), Fm-257 (~100 day half life), and Md-258 (~52 day half life). The last one never forms in fission reactors and can only be formed in particle colliders.

**Comment by BlueCreeper160** [comment]
And why not create light isotopes, like cobalt-60 and calcium-48, if is installed gregtech CE or another mod that have this elements.

**Comment by turbodiesel4598** [comment]
Due to the emergence of the [QMD addon](https://www.curseforge.com/minecraft/mc-mods/qmd) for NuclearCraft's overhaul version, there are currently no active plans from me to add any particle accelerators to base NC. This may change in the future, but due take a look at this new addon if you are looking for particle physics!
