### ISSUE TITLE
Feature Request: Turbines

### ISSUE THREAD

**Issue by Keridos** [turbodiesel4598/NuclearCraft#5]
Since big-reactors seems to be dead (9 months since last update) and this mod seems to not really have any turbines in it, I suggest adding in turbines for more effective energy generation.
As far as I know that would be really close to real life scenarios as well.
What I'd consider adding a slightly more complex system than BR does, basically allowing different coolant liquids (water/steam,cryotheum etc.) and in addition to variable coil material also more options for the material of the blades. Stronger materials mean that it can spin faster and improve efficiency by a bit. The energy production should depend strongly on the coil material though.

**Comment by turbodiesel4598** [comment]
I can't really say too much in detail yet, but I plan, after the particle accelerator, to really enhance the fission part of the mod - I want to add centrifuges and turbines as more efficient ways of getting U-235 and RF, respectively ;)

**Comment by turbodiesel4598** [comment]
Haven't commented here for a while, but this is how I see things happening:
Currently there is a temporary system in place involving steam and denser forms of steam that needs to be decompressed.
After I've updated the mod to MC 1.10, I want to have a different type of fission reactor in the game. The RF-producing one (passively cooled) will, as ever, require fuel cells of solid fissile material to run.
I plan on having a steam-producing reactor which requires molten salts of fissile material as fuel (a molten salt reactor). These fuels will require more work to create (more intricate processing system, involving fluorides, centrifuging etc.), but the reactors will overall produce more power (perhaps roughly 75% more power).
The structure of the actively cooled, molten salt reactors will be similar to the passively-cooled ones, except for obvious differences such as ports for water/steam input/output and the passage of the molten salt.
I haven't quite figured out exactly how the steam turbine generator should look or function, but I have two options. Either I go for a BR or Mekanism style turbine, which is essentially a big multiblock with a big, in-world turbine at the centre, or I go for a GregTech or Railcraft style turbine, where a multiblock is built, and then a turbine is placed in a GUI. Personally, I'm leaning towards the latter, because it gives me much more freedom when it comes to the interior structure of the turbine multiblock, but I will set up a poll on the Minecraft Forum thread and see if there's a clear favourite :)
