### ISSUE TITLE
[Suggestion] modular registering configs + rock crusher output config

### ISSUE THREAD

**Issue by Genesiz13** [turbodiesel4598/NuclearCraft#520]
Amazing mod, probably my favorite mod just for representing real life nuclear physics. However, one thing that i think would help is the option to disable the registration of certain parts of the mod. for example, the option to disable all fusion, salt reactors, heat exchangers, etc blocks and fluids. that way you can choose which parts of the mod are available. the reason being that if the player has no interest in steam production, or using molten salt reactors over the regular fission reactors, the mod registers a ton of blocks and fluids that never get used. adding this config would decrease load times for alot of people and overall reduce clutter in jei for example.  if you just use the fission and fusion reactors for example, all the fluids and bucket items are extra. otherwise maybe an option where you can disable just the fluid versions of fuels. also, currently, the rock crusher has certain outputs like sulfur, silver and aluminium that affect the balancing of other mods that add these items, effectively allowing you to generate infinite silver, aluminum or sulfur if you have a granite/diorite/andesite generator ( like thermal expansions igneous extruder) so perhaps a config to change the percentages of the rock crushers outputs, just for balancing reasons. anyway, keep up the good work :)

**Comment by turbodiesel4598** [comment]
Hey there!

Right now, there are options in the configs to disable parts of the mod, including the processors, passive resource generators, tools and armour.

However, this is actually a really horrible feature from a develompent point of view because I have to continually explicitly handle cases where certain things aren't registered to the game and so on, which takes up a decent amount of time and just makes the code less easy to work with, and for that reason I may actually move away from them when the mod mechanicvs are overhauled in a couple months or so, instead moving to a system where things like the crafting recipes and JEI entries are removed, which doesn't involve the nasty optional registration (Forge definitely does not recomment doing this anyway).

When this overhaul occurs, there will also be a few less blocks used for the construction of the multiblocks, but the main source of block ID use is in the fluids, but by default in the configs the registration of the fluids as blocks should be disabled, so you may want to check that in case it is enabled for some reason.

The rock crusher one is slightly more subtle, because unless something like TE is installed, those rock types are not meant to be infinitely available. Changing the configs doesn't do much really, because all that will happen is that you'd build more extruders and rock crushers. Instead the best thing to do may be to add a config to tweak the rock crusher recipes to not generate any materials that other mods use, instead only generating the NC gem dusts - would this work?

**Comment by turbodiesel4598** [comment]
Added rock crusher alternate recipes in v2.17a ;)
