### ISSUE TITLE
[1.12.2] Crash on modifying tile entity

### ISSUE THREAD

**Issue by ToMe25** [turbodiesel4598/NuclearCraft#572]
The NuclearCraft version 2.18 crashes if you modify a tile entity(for example the Salt Mixer) by for example putting a Upgrade in or letting it finish a recipe.

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!
https://pastebin.com/8VwbcqD3

**Comment by Ahndrek-LiCyri** [comment]
Can confirm, seems to be a issue with any of the UI's.
I have the same issue with the ManuFactory ([https://pastebin.com/HzMjQpFP](url)).
Simply clicking on the UI of it causes a insta-crash.

**Comment by ToMe25** [comment]
i have tried a few more machines and they all crashed too.

**Comment by Ahndrek-LiCyri** [comment]
Same as well. Something definitely broke all the UI's, which really sucks because none of the machines are usable now. This is quite the serious bug.

**Comment by turbodiesel4598** [comment]
Strange, didn’t happen in testing. I’ll get a fix out pronto!

**Comment by turbodiesel4598** [comment]
In the meantime fellas, does this happen if only MC is installed?

**Comment by Paul17041993** [comment]
Confirmed here as well, albeit with 175 or so other mods.
https://pastebin.com/0DEdj827

**Comment by ToMe25** [comment]
"does this happen if only MC is installed?" i mean i tested it with only nc and ccl so i guess it does.
i can test it again without ccl later if you want me to do that, but i always test crashes with the least other mods* i can before reporting.

*besides ccl because removing that sometimes causes trouble for me and most mods need it anyways

**Comment by Paul17041993** [comment]
Oh, turns out it also crashes the server if another mod accesses the inventories, so it's not just the UI...

**Comment by ToMe25** [comment]
yeh its the tile entity itself.

**Comment by bigenergy** [comment]
some crash 
https://paste.dimdev.org/yebufexevu.sql

**Comment by theshadowake** [comment]
Also having the issue:

https://paste.dimdev.org/qehazekobi.mccrash

**Comment by turbodiesel4598** [comment]
I _think_ I've fixed this, as it seems to no longer crash for me outside of the dev environment. Perhaps you could try [this build](https://www.dropbox.com/s/nk5f4p8wav7xu10/NuclearCraft-2.18a-1.12.2.jar?dl=0) before I upload to CF?

**Comment by Atagait** [comment]
Potentially related error (using any machine crashed): https://paste.dimdev.org/otegalohev.mccrash

The 2.18a build seems to have fixed it

**Comment by turbodiesel4598** [comment]
Great! I'll get it on CF now then :)

The issue was that these machines implemented an interface which was also called `markDirty()`, used in the code related to item handling. When trying to implement this method in the main TE superclass, the Java compiler interpreted this as an override of only the base TE `markDirty()` method, ignoring the interface as that is only introduced in the subclasses used for the item-handling TEs. This meant that when the item-handling code looked for the implementation of the method, it couldn't find it, hence the 'abstract method' error. For some reason, the built-in Eclipse compiler on the other hand was able to deduce the correct method to refer to, so this slipped through testing :P

Anyways, it's sorted now. Thanks for the reports everyone!

**Comment by cmoates** [comment]
Can also confirm this fix works for me. Thanks for your quick turnaround!

**Comment by turbodiesel4598** [comment]
Would have been a bit snappier, but had extended family round from Canada today... played a cricket match and it took about as long to explain the rules as it took to play.

**Comment by Ahndrek-LiCyri** [comment]
Thank you! Works fine now.
And hey, family first man :)
