### ISSUE TITLE
Compatibility with Ultimate Car Mod: Methanol in UCM machines stuck

### ISSUE THREAD

**Issue by database64128** [turbodiesel4598/NuclearCraft#575]
According to the author of Ultimate Car Mod https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod/issues/72 NuclearCraft is conflicting with Methanol in UCM. Is there a way to fix this?

**Comment by turbodiesel4598** [comment]
Not really no. This should be fixable on their side, but as their source code is not visible I can't see where the problem is. If they're trying to get a reference to the fluid by just pointing to their fluid's instance, then they need to instead get the correct one through referring to the fluid registry.
