### ISSUE TITLE
Crash w/ Wearable Backpacks & Hardcore Containers

### ISSUE THREAD

**Issue by nephatrine** [turbodiesel4598/NuclearCraft#606]
I am getting random crashes every so often and it seems to be due to NuclearCraft and the backpacks from [WearableBackpacks](https://www.curseforge.com/minecraft/mc-mods/wearable-backpacks). I do have radiation_hardcore_containers enabled and assume that is the cause. I have not seen any other containers throw up this same error.

https://pastebin.com/sYHp1KzM

Ideally whatever interaction is causing this crash could be resolved, but as a stopgap is there a way we can maybe get a blacklist in the config to stop certain container entities from having the radiation mechanic and keep it on others? I can see such a feature being useful for modpacks even outside of preventing errors like this since some other mods might add containers that should conceptually be more shielded that a modpack maker might want to exclude from this feature.

- forge-1.12.2-14.23.5.2838
- NuclearCraft-2.18k-1.12.2
- WearableBackpacks-1.12.2-3.1.4

**Comment by turbodiesel4598** [comment]
I think this is a Wearable Backpacks bug - it should not be null-pointering when NC [asks for the capability](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/src/main/java/nc/radiation/RadiationHelper.java#L70).

It's happening because the tile returns [this](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/block/entity/TileEntityBackpack.java#L185), which feeds a null world to [this](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/misc/BackpackDataItems.java#L47), which then causes a null-pointer [here](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/misc/BackpackDataItems.java#L72) ;)

**Comment by copygirl** [comment]
You're right. Heck, I even noted that [over a year ago](https://github.com/copygirl/WearableBackpacks/issues/76#issuecomment-380880315).

I think the crash only occurs from loot backpacks that have been dropped by entities that spawned with them. So another option to fix this would be to disable the "Spawn Naturally" option in the entity settings.
