### ISSUE TITLE
Graham Cracker recipe lacks ore dictionary support

### ISSUE THREAD

**Issue by TheDeviantCrafter** [turbodiesel4598/NuclearCraft#609]
The Graham Cracker recipe in the Pressurizer only works with Nuclearcraft's flour. It should use any item with the `dustWheat` ore dictionary tag to make it compatible with Natura flour.

**Comment by turbodiesel4598** [comment]
[I already am using that ore dict entry to specify the recipe.](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/PressurizerRecipes.java#L31) Is it not working as you would expect?

**Comment by TheDeviantCrafter** [comment]
Natura's wheat flour, which has the same ore dictionary entry, does not work with the recipe. I found a similar issue with recipes using `itemSilicon`.

**Comment by turbodiesel4598** [comment]
[It seems they're registering it as `foodFlour` rather than `dustWheat`.](https://github.com/progwml6/Natura/blob/1.12/src/main/java/com/progwml6/natura/oredict/NaturaOredict.java#L60-L61) I'll add the former and that should fix things!

As for `itemSilicon`, is that from AE2? If so, for some reason they don't add their item to the ore dict if another mod already has.

**Comment by TheDeviantCrafter** [comment]
I used CraftTweaker to add the ore dictionary tag to Project Red's silicon. That may be related. Could Nuclearcraft be checking ore dictionary tags before CraftTweaker alters them?

**Comment by turbodiesel4598** [comment]
If so, perhaps try removing the recipe and re-adding it through NC’s CT integration ;)

**Comment by turbodiesel4598** [comment]
Added `foodFlour` as a valid ingredient for the graham cracker recipe ;)
