### ISSUE TITLE
default fusion power of H-T fuel too low ?

### ISSUE THREAD

**Issue by ToserBan** [turbodiesel4598/NuclearCraft#610]
Just a question,
In the nuclearcraft.cfg has the H-T fuel combo just 0.3 base power. Shouldnt it have power similar to H-He3 , which has 3036, more than 10000 times more than H-T ? Helium 3 is similar to tritium, so the differences shouldnt be so big and tritium has only one proton so we need not so high temperatures to overcome the electromagnetic force.

**Comment by turbodiesel4598** [comment]
The reason it's significantly different is because H-T produces Helium-3, while H-He3 produces Helium-4. The difference in mass between the initial and final particles in the former is much lower, mainly because Helium-3's binding energy is nowhere near as large as Helium-4's, so the energy released is much lower also ;)
