### ISSUE TITLE
Can’t change time, energy usage, etc. in a CraftTweaker alloy furnace recipe

### ISSUE THREAD

**Issue by Dimentive** [turbodiesel4598/NuclearCraft#616]
`mods.nuclearcraft.alloy_furnace.addRecipe(<ore:ingotPlatinum>, <ore:ingotOsmium>, <contenttweaker:plasmium_ingot>, 2, 2, 3);`

Getting “a method available but none matches the parameters (string)” errors.

1.12.2
Forge 14.23.5.2847

**Comment by turbodiesel4598** [comment]
@Dimentive You have to [make sure the values are floating point](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt#L67-L68), i.e. `2.0, 2.0, 3.0` ;)

**Comment by Dimentive** [comment]
**Oh!** Thank you. It’d be great if examples were included in the [help file](https://github.com/turbodiesel4598/NuclearCraft/blob/master/craftTweaker.txt).

**Comment by Dimentive** [comment]
`mods.nuclearcraft.alloy_furnace.addRecipe(<ore:ingotPlatinum>, <ore:ingotOsmium>, <contenttweaker:plasmium_ingot>, 1.0, 25.0, 1.0);`

This is getting errors too.

**Comment by turbodiesel4598** [comment]
Ah, that's because y[ou need to surround all of the arguments in an array](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt#L4). That was changed in more recent version if the mod, so I forgot about that.
And [the docs do include the info](https://github.com/turbodiesel4598/NuclearCraft/blob/1.12.2/craftTweaker.txt#L67-L68), though it may be easy to miss it ;)

**Comment by Dimentive** [comment]
Oh, I missed that. Thank you! 💙
