### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by Fortist** [turbodiesel4598/NuclearCraft#62]
So, I finally got into my main world to try the new update and it seems that you're messing with health in a way that it removes all bonus health gained by other mods, and I cant seem to get it back.  My android powers are trying to regain the lost health and I keep getting the "Damaged" screen shake every so often.

Ah well. Going to have to revert.

**Comment by accessdenied0** [comment]
I seem to found the reason for my health-bar problem. I also experienced that my maximum hearts are reduced after I used the creative gamemode for a second.

Anyway I updated to **NuclearCraft-1.9d** and it happened. In the mean time the update was changed to a BETA release (probably because of the upcoming 1.10 update). I got this health problem.

After an "update" or exchange was showed me on Curse, I updated the the "NuclearCraft-1.9d" to NuclearCraft-1.9d files, because I presumed a bugfix...

Sadly with this update I wasn't able to load my world anymore because a (probably config related) [crash](http://pastebin.com/i6GkKSC7). I noticed the change in FILE-CHANGELOGS, the arrangement with the files and my mistake and I downgraded back to **NuclearCraft-1.9c**. But unfortunately didn't fixed it the health problem. 

2 Hearts (4 half-hearts) are gone. I had to fix it with the NBT-Explorer (set (level.dat/Data/Player/HealF) from 16 to 20 again.).

I hope this helps a bit.

**Comment by Fortist** [comment]
Well, what you experienced was having a ton of radiation. as far as I know.  Or just maybe my mods counteract it. Anyway, I didnt have to do anything special other than downgrade and get all my hearts back. (like 89 hearts, tinker's and a heart mod)

**Comment by turbodiesel4598** [comment]
Hopefully this helps - here's a stable build without the radiation mechanics: https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2330045
This is certainly recommended for those who simply want to update the mod for their long-term worlds, but remember to turn off all Fission Reactors before updating!
