### ISSUE TITLE
[NCO] Heavywater in Mekanism can't be processed in the Electrolyzer anymore?

### ISSUE THREAD

**Issue by ChromaPIE** [turbodiesel4598/NuclearCraft#639]
Maybe it's because the difference between the IDs, <<fluid:heavywater>> in Mekanism and <<fluid:heavy_water>> in NCO. But it's weird that in the pre-overhaul version this recipe can be successfully processed. So I'm wondering that weather this fluid ID has been changed in NCO? If so, it is suggested to add an official compat for the heavywater in Mekanism. thx.

###### And by the way it is possible to make a compat with Mekanism Heat? Like an output hatch which can output the heat from NC heat-producing multiblocks that can be used to heat up some Mek multiblock machines like the boiler through the Thermodynamic Conductor in Mek. To be honest, the recent way in Mek of producing heat is way too boring, Forgive me for the idea that hoping for a more interesting way of producing heat, as in NCO there are a sea of exciting brand-new fuels that is designed for heat which in fact is not related to Mek heat at all. Hope it's not too rude. XD.

**Comment by turbodiesel4598** [comment]
This is actually intended now, due to how Mek and NC interacted in the pre-overhaul version. Mek made getting deuterium far too easy, which made the power generation landscape for many players across many modpacks rather bland. NC will still allow for Mek's heavy water to be used to make heavy water moderators, but its deuterium and tritium will not be usable in NC machines.
