### ISSUE TITLE
Reactor cooling block recipes

### ISSUE THREAD

**Issue by Nocty201** [turbodiesel4598/NuclearCraft#64]
Hello!

Am building a pack and some of the cooling blocks don't have a recipe in NEI. Some of the cooling blocks (Redstone and Glowstone) show up in NEI with the info, but not the recipe. At a guess, it might be because I lack TE (my mod list is [here](http://acrididae.playat.ch/legalstuff/)). I also have Cryotheum blocks, despite the lack of TE.

I'm fine with modtweaking a recipe to make it all work, but wanted to check in to be sure I've not made an error elsewhere. Would love some advice.

Thanks!

**Comment by QuantumTraverse** [comment]
The blocks continue to exist in the mod whether TE is installed or not. TE only determines whether they are craftable or not.

**Comment by Nocty201** [comment]
Alright, I just wanted to check as some mods disable non-relevant recipes
if the other mood isn't installed.  I'll modtweak in some of my own recipes
and leave the script here in case others are interested in the future.

Thanks!

**Comment by turbodiesel4598** [comment]
I think it would be a good idea to add 'vanilla' recipes for the advanced coolers in case TE isn't installed :)

**Comment by chaos234** [comment]
Or you can wrap a small line of code to not register blocks if other dependet mods are not present.

E. g. if IC2 isn't present so why implementing the Coolent Block? Same should go to all other Blocks which requiring other mods to be created.

In addition you can use the config e. g. "ic2=true/false" therm_exp=true/false"; so that we can choose if we want the additional blocks or not but this is also a bit kind of cosmetic ^^.

**Comment by turbodiesel4598** [comment]
I don't want to not register them in case a player without IC2 installed, for example, joins a server with IC2, and crashes. I can just remove them from NEI and the creative menu so that the player doesn't see them. In the 1.10.2/1.11.2 version, this won't be a problem and will sort itself automatically, as the recipe for the enderium cooler uses enderium ingots, from the ore dictionary, and the cryotheum cooler uses the cryotheum dust, again from the ore dict.
