### ISSUE TITLE
Can't figure out how radiation works

### ISSUE THREAD

**Issue by Felthry** [turbodiesel4598/NuclearCraft#646]
I'm just starting on nuclearcraft (on 1.12.2) for the first time, and I can't seem to find any information at all about how radiation works. Do I need to be worried if I have a chest full of uranium blocks? What about blocks placed in the world? Ingots dropped on the ground? What produces radiation, at what level is it something to be concerned about, how do I manage it when it is a problem, and where should I go in the future to find information like this?

**Comment by turbodiesel4598** [comment]
@Felthry Hey there! Radiation in NC is designed to be rather configurable and packs tend to mix things up a bit, but if you're playing with the default configs, this video should still be 90% accurate.

The tl;dw is that blocks inside chests will not cause any problems (unless 'hardcore containers' is enabled), blocks around the world will only contribute radiation very slowly (because block checks are laggy), tile entities can generate radiation depending on what they are (reactors, etc.) and items dropped on the ground or in your inventory will contribute radiation.

The rough level to be worried about is something like a few mRad/t, at which stage the natural player radiation level decay is definitely not fast enough to deal with the environment.

The best place to be for quick info is definitely the Discord server - it's pretty active and many people there can help you with most questions :)

**Comment by Felthry** [comment]
You mention "this video", but there isn't a link to a video. I think you forgot a link?
I'm really not a fan of joining random discord servers. Social anxiety makes that kind of thing really hard for me; in the interest of accessibility I'd like to propose adding this information to a wiki somewhere at the very least, with an in-game guide book as the best (though probably hardest to implement) option.

**Comment by turbodiesel4598** [comment]
Whoops, I forgot to link it :P [Here it is :)](https://www.youtube.com/watch?v=4KDPInVMPcE)
I do plan on in-game documentation for the overhaul branch of the mod, but probably won't appear in the pre-overhaul branch as I have stopped development for it.
