### ISSUE TITLE
something wrong in NuclearCraft CraftTweaker Recipe Addition and Removal

### ISSUE THREAD

**Issue by Woody-0w0** [turbodiesel4598/NuclearCraft#660]
NuclearCraft 2.x for version **1.12.2** is no longer being developed as the focus of attention has been shifted to the overhaul. Bugs reports will be responded to, but new features will no longer be accepted! Hopefully you can understand that working on two branches of this project at once is far too time-consuming!

Please use a paste tool such as Pastebin (https://pastebin.com) for crash logs!

//============================================================
when i write according to “mods.nuclearcraft.chemical_reactor.addRecipe([fluidInput1, fluidInput2, fluidOutput1, fluidOutput2, {double timeMultiplier, double powerMultiplier, double processRadiation}]);” as:
mods.nuclearcraft.chemical_reactor.addRecipe([[<liquid:lava>*2000],[null],[<liquid:borax_solution>*333], [<liquid:sulfuric_acid>*333], {400, 5, 0}]);
or:
mods.nuclearcraft.chemical_reactor.addRecipe([<liquid:lava>*2000,null,<liquid:borax_solution>*333, <liquid:sulfuric_acid>*333, {400, 5, 0}]);
or:
mods.nuclearcraft.chemical_reactor.addRecipe(['<liquid:lava>*2000','null','<liquid:borax_solution>*333', '<liquid:sulfuric_acid>*333', {400, 5, 0}]);
in scripts files
they all wrong.
what hanppened?
Please show us a complete example.

**Comment by Woody-0w0** [comment]
mods.nuclearcraft.salt_mixer.removeRecipeWithOutput([<liquid:boron>]);
dont work either

**Comment by turbodiesel4598** [comment]
Hey there,

CT ingredients need triangle brackets, e.g. `<ore:ingotIron>*4` or `<liquid:sulfuric_acid>*333`, and as the docs say, you don't want to include the curly brackets on the optional arguments (those optional arguments also needs to be explicitly written as floating point numbers if required, e.g. `400.0` rather than `400`).

In the end, you would have something like:
`mods.nuclearcraft.chemical_reactor.addRecipe([<liquid:lava>*2000, null, <liquid:borax_solution>*333, <liquid:sulfuric_acid>*333, 400.0, 5.0, 0.0]);`

Also be aware that a time multiplier of 400 will make the recipe incredibly slow :P

Hope that helps!

**Comment by Woody-0w0** [comment]
> Hey there,
> 
> CT ingredients need triangle brackets, e.g. `<ore:ingotIron>*4` or `<liquid:sulfuric_acid>*333`, and as the docs say, you don't want to include the curly brackets on the optional arguments (those optional arguments also needs to be explicitly written as floating point numbers if required, e.g. `400.0` rather than `400`).
> 
> In the end, you would have something like:
> `mods.nuclearcraft.chemical_reactor.addRecipe([<liquid:lava>*2000, null, <liquid:borax_solution>*333, <liquid:sulfuric_acid>*333, 400.0, 5.0, 0.0]);`
> 
> Also be aware that a time multiplier of 400 will make the recipe incredibly slow :P
> 
> Hope that helps!

it works! thanks a lot

**Comment by turbodiesel4598** [comment]
Awesome :)
