### ISSUE TITLE
NuclearCraft Fission Control causing TPS issues when in tight on/off loop

### ISSUE THREAD

**Issue by salomj** [turbodiesel4598/NuclearCraft#681]
According to the timing reports, the "nc.tile.generator.TileFissionController$New" sometimes takes up to 90% of a tick between my three reactors. It appears that every time I start/stop the reactor, it is creating several new java classes, and each time this class is created, it is taking 6.46ms.

My three reactors are all set up with a comparator to prevent overheating which causes the reactor to rapidly turn off and on.

It is worth noting that in my timing report, I only had 908 ticks, but somehow this class was created 4505 times. Which means between the three reactors, each reactor called this class an average of 1.65 times per a tick, which seems really odd to me.

I'm playing All The Mod Remix 3 - 1.6.0 which uses NuclearCraft-2.18u-1.12.2. 

My current work around is to feed all the reactors into a very large battery which then discharges slowly, so the rapid on and off is only an issue for less play time.

**Comment by turbodiesel4598** [comment]
Hmm, I really don't know what the new instances could be, or why they're taking so long to be created. Turning the reactor on and off rapidly will cause lag simply due to how the thing was implemented though, so I'm afraid I really don't think I'm going to be able to find an easy solution, particularly as I'm not working on that branch of the mod anymore. I just suggest removing the comparator and instead having a heat-negative or neutral reactor which runs continuously.

**Comment by turbodiesel4598** [comment]
Closing this as I'm moving away from supporting the pre-overhaul version of the mod. Sorry to anyone who still has this problem!
