### ISSUE TITLE
Integration with IC2/GregTech?

### ISSUE THREAD

**Issue by Rongmario** [turbodiesel4598/NuclearCraft#69]
Anyway of integrating with GregTech as the mod adds forms of plutonium? Ore dictionary with minetweaker just doesn't cut it and is kinda funky in they don't really have the same isotope etc.

**Comment by Rongmario** [comment]
Just to add: happens with other elements too. I'll try compile a list.

**Comment by Rongmario** [comment]
EDIT: When musing MTweaker to remove gregtech's Thorium smelting recipe, NuclearCraft's Thorium Ore to Thorium Ingot recipe decided to stop working despite it being in NEI.

**Comment by chaos234** [comment]
I am not the owner of this mod but I have an idea how to work arround this bug.

Simple way will be to block the generation of Uranium/Thorium and other mats which are already
supplied over GT. Also changing a few recipes so that they fit GT style should then be possible if I can 
get the full GT Material List (which contains the programmed information what ID uranium/thorium would be).

At the End it must then be tested twice but it should work I think. So let me try what I can do oh and do you want it for GT5U or for which GT version?

**Comment by Rongmario** [comment]
Thing is, love it to be GT5U but how NC registers its materials in the oredict are absurd, such as Pu239 is registered as literally Pu239. And NC machines doesn't use OreDict either.

**Comment by chaos234** [comment]
What is the problem with the registration in the OreDict with it? That it isn't lovercase?

And that NC Machines don't use OreDict ... Eventually wanted or only forgotten about it.
Because some crafting recipes are also not going over the ore dict like the creation of the
upgrade modules in the Induction Smelter.

In fact I can take a look on it but if this is a good idea I don't know and I must test all the stuff
too but I have noted it and will see, what I can do.

**Comment by chaos234** [comment]
I looked at it but it seems ok for me so what is false with the name under the Pu239 (or others) are registered?

Fixing the missing OreDict Support may be possible but this is another Topic ;).

**Comment by turbodiesel4598** [comment]
Sorry about the funny oreDict entries - they were being used for NC recipes only when I first decided to use them.

I'm not super familiar with GregTech - do you know what the materials it adds are, and what their OreDict names are? If so, I could easily add them.

**Comment by indoorsNB** [comment]
I think `minetweaker` can use a command on console list all oreDict `/minetweaker orexxxxx`(Sorry I forgot, but I think you can try `/minetweaker help`?)
If you can add a setting in config that can change processing in machine( like gregtech6 recipes folder) , it might be very interesting.

**Comment by chaos234** [comment]
GreagTech has an unification system. So if you have over 10 different copper ingots it will be unified to one copper ingot (mostly the GT version).

This is applied to all oreDict entries if I am right.

I think it is better to join on there discord server (look here for more information: http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488). Pleaase not that the discord server seem to be for the unofficial version from Blood Asp (I have never seen GregoriusT in there). So for the original plugin you should go into the esper.net irc and /join #GregTech :).

Before questioning like "Why are there two different version of the mod." ... it is better to read the threads on the IC2 Board otherwise comment like "lt;dr" are possible ^^.

I hope you can get through the code but if not I am sure you will get help from the dev's there :).

**Comment by Rongmario** [comment]
Haven't seen this thread bump haha, turbo, we can chat about this if you need more information.

**Comment by turbodiesel4598** [comment]
Been a while since I've had the time to think about this mod! I'll take a look at GT and see how it deals with its plutonium ,and then work on a simple way to intertwine its mechanics with this mod :)

**Comment by Rongmario** [comment]
We are tweaking the Plutonium stuff in GT right now, as the isotopes are a little messed up, since we tried to match IC2's plutonium.

**Comment by turbodiesel4598** [comment]
Is this still something to look into?

**Comment by Rongmario** [comment]
It is not from what I gather! We've been updating GregTech to 1.12.2, see you on there :P

**Comment by Rongmario** [comment]
I'll leave it open and double-check if there is anything that'd be cool with GT compat in 1.12.2, the repo is here: https://github.com/GregTechCE/GregTech

**Comment by turbodiesel4598** [comment]
Sure thing - if you add various nuclear-related stuff to the ore dictionary, let me know and I'll try to add some NC recipes using them in preparation :)
