### ISSUE TITLE
[Overhauled] Issue extracting steam from Fission Reactor Vent

### ISSUE THREAD

**Issue by TrinityC9** [turbodiesel4598/NuclearCraft#702]
I am using NuclearCraft-2o.4.7-1.12.2.jar

I don't know whether I'm missing something, but It seems I'm unable to extract the steam from the Fission Reactor Vent.

I've Tried: EnderIO, Thermal Dynamics, Mekanism (fluid and gas), Extra Utilities and Applied Energistics 2 (fluid & extra cells 2 gas).

Nothing seems to be able to get the High Pressure Steam out of the  Fission Reactor Vent.
Water can be pumped in through any fluid transport methods.
But the steam doesn't seem to want to leave the reactor.

**Comment by miner7000000** [comment]
same here, cant even input steam directly into the turbine with creative mode tanks

**Comment by turbodiesel4598** [comment]
@TrinityC9 @miner7000000 The vent needs to be switched to output mode with a multitool ;)

**Comment by miner7000000** [comment]
@turbodiesel4598 thank you so much man I had no clue what so ever.

**Comment by miner7000000** [comment]
@turbodiesel4598 its outputting steam now but the turbine still wont accept it. what do I do?

**Comment by miner7000000** [comment]
nevermind figured it out

**Comment by turbodiesel4598** [comment]
What was it?

I'll also close this issue now :)

**Comment by miner7000000** [comment]
I never turned on the controller for the turbine with redstone, my mistake.

**Comment by ProxyPlayerHD** [comment]
it should really say that in the description of the blocks or the tool because i've run into the same exact issue and the tutorial on the YT channel was made before the Input/Output thing existed so besides experimenting there is pretty much no way to know this.

also why only the Multitool? I've tried it with the Crescent Hammer before finding this post as that used to the THE Universal Wrench but it didn't work...
