### ISSUE TITLE
Question regarding the sources of the recipes

### ISSUE THREAD

**Issue by DarkShadow44** [turbodiesel4598/NuclearCraft#717]
Using the overhaul version of the mod.
Out of curiosity, mind asking how you came up with the recipes?
There's a lot of isotopes in the mod, and a lot of reprocessing and decaying. How did you decide which nuclear fuels exist, how they would be reprocessed once depleted and how isotopes can be "decayed"? Are there real sources regarding that matter or is it partly sci-fi? It seems hard to find on google, at least.

**Comment by QuantumTraverse** [comment]
For the most part, isotope decays recipes come from the radioactive decays that occur in real life. The only exception is that some isotopes get skipped over in the in-game decays to preserve balance (For example, in-game Pu-241 decays into Np-237 directly, rather than going to Am-241, since Am-241 can be made into an RTG, which is infinite free power).

Nuclear fuels consist of two parts: fissile and fertile isotopes.  The fissile isotope is the one after which the fuel is named: e.g. LEU-235 contains the fissile isotope Uranium-235. The fissile isotopes chosen in-game, which control what the different fuels are, are all actual fissile isotopes in real life. The fertile isotopes used in-game, such as Uranium-238 and Plutonium-242, are usually only approximately fertile in real life; they are often also fissile, but only for fast neutrons, as one would have in a nuclear explosion, rather than being fissile to thermal neutrons, which are found in nuclear reactors. The relative balance of which fissile isotopic fuels produce more heat is approximately correlated to the real life fission cross sections, which control how likely a nucleus is to undergo fission, but the correlation is not exact. The efficiency value assigned to each fuel really has no basis in reality; it is just a system to incentivize the players to aim to travel up the fuel tree.

Reprocessing fuels is actually the part where the mod differs most from reality. In reality, reprocessed fuels do not yield nearly as much transuranic isotopes as is depicted in-game. They tend to contain only small amounts Plutonium-239, and only even small amounts of anything higher.

**Comment by turbodiesel4598** [comment]
Good answer :P
