### ISSUE TITLE
Client crash, looks like a NuclearCraft error

### ISSUE THREAD

**Issue by indoorsNB** [turbodiesel4598/NuclearCraft#74]
I don't know what happened, but when I join to my server, client crash. I restart the game and join the server, crash again, same problem. I think it is nuclearCraft's bug.
http://pastebin.com/b5ufke3P

**Comment by indoorsNB** [comment]
This error let my client can't join the server

**Comment by turbodiesel4598** [comment]
Can you join single player worlds?

**Comment by indoorsNB** [comment]
Yes, single player is working

**Comment by indoorsNB** [comment]
After I delete the world file on server and restart, I can join my server again. But got kick out after a few minutes and can't join server anymore, but I lost the logs : (

**Comment by turbodiesel4598** [comment]
Hmm - might be a similar issue to this one: https://github.com/SleepyTrousers/EnderZoo/issues/45 ... I'll look for a fix, but I'm not exactly sure what that may be.

**Comment by indoorsNB** [comment]
thank you  👍

**Comment by turbodiesel4598** [comment]
The only info I can find on this is that the crash is being caused by an entity ID mismatch between the server and client, and I have no control over that as Forge handles it automatically, so I can't see how this could be fixed without starting a fresh server with fresh configs. Sorry I couldn't find a better solution.
