### ISSUE TITLE
[1.12.2] Manufactory flips around if block infront of it.

### ISSUE THREAD

**Issue by itzTheMeow** [turbodiesel4598/NuclearCraft#762]
This is in the skyfactory 4 modpack version.
The manufactory flips its rotation axis when you put an item in it and theres a block infront of it.
setup:
![image](https://user-images.githubusercontent.com/50887230/134265556-7b26f441-1c21-4417-99cf-7533ad2dbc19.png)
block infront
![image](https://user-images.githubusercontent.com/50887230/134265580-7f1812ce-2ea6-4624-bbe4-464e55d4a72d.png)
item in:
![image](https://user-images.githubusercontent.com/50887230/134265598-aff9a713-d2f0-4d4f-bb13-421f82a0f615.png)
flipped:
![image](https://user-images.githubusercontent.com/50887230/134265602-eeafdd32-d9c2-4874-a667-3b9f5395981b.png)

This does not happen if there is a block on both sides (in this case east and west)
This is an issue mainly because if you make a chisels and bits block to go infront of it, it flips around.
![image](https://user-images.githubusercontent.com/50887230/134265679-fadc89fa-94df-42d1-bf84-fe2fc1b1132b.png)
![image](https://user-images.githubusercontent.com/50887230/134265685-f33a4590-f7f7-42eb-b75b-533e436f126f.png)

**Comment by tomdodd4598** [comment]
Good spot! Unfortunately, I don't think this is fixable, at least without compromising the logic which determines the direction the machine faces when it is placed - I am pretty sure it is a consequense of how I implemented the idle and active states of the machines (using distinct blocks rather than blockstates), because it doesn't happen in NCO. Hopefully it isn't too much of an issue!
