### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Cazadorsniper** [turbodiesel4598/NuclearCraft#77]
https://pastebin.com/gFzJvJNz for 1.10.2

**Comment by turbodiesel4598** [comment]
Hmm... strange - I will have to install that pack myself and see what happens. It's really unclear to me what the issue is though - apparently classes aren't being found or initialised, but I'm almost certain they should be. My one thought is that Tesla might have something to do with it, but again, I thought I'd already fixed issues like that before release. I'll do some testing and come back to you :)

**Comment by Cazadorsniper** [comment]
Well, the pack is suppose to be as light as possible so my limit is 130 mods and we're at 129 without NuclearCraft.

**Comment by Cazadorsniper** [comment]
so the pack starts up fine with IC2 in the pack on 1.10.2 but 1.11.2 starts up fine without IC2.

**Comment by turbodiesel4598** [comment]
I see - I _might_ have found the issue, but I'll do some testing - thanks for the help.

**Comment by Dovahkiin-Warrior** [comment]
![image](https://cloud.githubusercontent.com/assets/16886014/24989646/16151710-1fdc-11e7-9ed3-38d4b9af5095.png)
As stated elsewhere, is there a 1.10.2 version that can be downloaded in which fixes this bug?

**Comment by turbodiesel4598** [comment]
I've just uploaded a new version that should fix the I18n issue: https://minecraft.curseforge.com/projects/nuclearcraft-mod/files

**Comment by turbodiesel4598** [comment]
Has the problem gone @Cazadorsniper ?

**Comment by Cazadorsniper** [comment]
yeah, it works now

**Comment by turbodiesel4598** [comment]
Awesome :)

**Comment by Weldera** [comment]
mcafee says that industrial craft you sent is a virus, every other mod in my life time has been fine... so what are you up to turbodiesel?.....
