### ISSUE TITLE
Crashed with GTCEu

### ISSUE THREAD

**Issue by Shepherd23333** [turbodiesel4598/NuclearCraft#786]
Latest GTCEu has broken the compat with NCO.
Here is the crash-report: https://paste.ubuntu.com/p/j9yGDpgQZX/

**Comment by GeoTerra** [comment]
Just chiming in to say that I'm experiencing the same error as above.

**Comment by ALongStringOfNumbers** [comment]
This will be fixed with #785, and is caused from some changes GTCEu made to its recipe classes

**Comment by tomdodd4598** [comment]
Now that I have some time again, I will get on this as soon as I can :)

**Comment by levicc00123** [comment]
I'm having the same issue with nuclearCraft underhaul.
[crash-2022-12-10_08.58.50-client.txt](https://github.com/tomdodd4598/NuclearCraft/files/10200419/crash-2022-12-10_08.58.50-client.txt)

**Comment by ferreiraalex** [comment]
me too
[crash-2023-01-31_20.24.36-client.txt](https://github.com/tomdodd4598/NuclearCraft/files/10549212/crash-2023-01-31_20.24.36-client.txt)

**Comment by GeoTerra** [comment]
Just wanted to bump this issue as it's almost been a year since this issue was opened and it still hasn't been fixed in the builds on CF. I know I could probably build from source as I THINK it's been fixed in this repo, but because I'm working on a modpack project as of almost a year ago, I'd like to be able to pull from CF on installation of the pack.

However, I 1000% understand if @tomdodd4598 got busy with life. It happens to us all. Life comes first, then hobbies like modding. I wish Tom all the best and thank you for your work.

**Comment by caniplzjustlogin4godsakesthistakesforev** [comment]
Bump, with best regards

**Comment by tomdodd4598** [comment]
Will be fixed very shortly on both NC's and GTCEu's side :)
