### ISSUE TITLE
Tough Alloy JEI no recipe

### ISSUE THREAD

**Issue by jjjworley** [turbodiesel4598/NuclearCraft#80]
NuclearCraft 2.0a-1.11.2

Can no longer click on recipe for tough Alloy in JEI and see what the recipe is.

**Comment by turbodiesel4598** [comment]
That's because Tough Alloy is now made in the Alloy Smelter and there is currently not JEI support for the machines. To make graphite, you put coal in the Manufactory, and to make tough alloy, first make steel in the Alloy Furnace with graphite and iron, then ferroboron with steel and boron, then tough alloy with ferroboron and lithium :)
