### ISSUE TITLE
[1.11.2] Crash on game load

### ISSUE THREAD

**Issue by EmosewaGamer** [turbodiesel4598/NuclearCraft#84]
Well when loading the new update on my pack the game crashed. I tested the mod by itself and I didn't get the issue. I don't get if it's due to some mod incompatibility in the update or what, but here's the log: https://pastebin.com/qeJWrSGu

**Comment by turbodiesel4598** [comment]
You need to reset your configs :)

**Comment by EmosewaGamer** [comment]
Ik that's why i closed it. Didn't see that the first time I read the log, but a minute after I opened the issue I did. You should have mentioned it in the update log though.

**Comment by turbodiesel4598** [comment]
You're right - I have now. I think I've found a fix though, so I'll get that up as soon as possible. The issue is that when I added new coolers, the size of the array of cooler stats changed, and so there was a mismatch between the size of the array in the config file and that of the defaults. What I'll do is check if the array sizes are the same, and if not, set the new members of the array in the file to the defaults automatically.
