### ISSUE TITLE
1.10.2 Fusion Reactor second fuel tank inaccessable

### ISSUE THREAD

**Issue by CJL48** [turbodiesel4598/NuclearCraft#97]
I cannot figure out how to load fuel into the second tank of the fusion reactor in NC 2.2. No matter how I place the fluid pipes, only the first tank is filled.

**Comment by turbodiesel4598** [comment]
Are you using the same fuel in each tank, or two different fuels?

**Comment by CJL48** [comment]
I tried different fuels after I couldn't get the same type of fuel into the tank. No fuel can be loaded into the second fusion reactor tank, regardless of how I place the pipes.

**Comment by turbodiesel4598** [comment]
I can't recreate this issue - are you on a server?

**Comment by CJL48** [comment]
No. Now that I think about it, I tried to fill the reactor with mekanism hydrogen- I'll do some testing and see if it works better with fuels from nuclearcraft.

**Comment by CJL48** [comment]
Experimented with the products of the nc eletrolyzer and an infinite tank- the second tank starts filling after the first is full. Going to see if I can get 2 fuel types going next.

**Comment by turbodiesel4598** [comment]
Helium (i.e. Helium-4) is not a legitimate fusion fuel - Helium-3 is, however. The electrolyser produces hydrogen, deuterium, tritium and oxygen. All of them but oxygen are legitimate fusion fuels, but the deuterium and tritium production rates are very low.

The possible fuels are hydrogen, deuterium, tritium, helium-3, lithium-6, lithium-7 and boron-11. You can get the first three from the Electrolyser, but can produce more deuterium and tritium as the products of fusion reactions (although there is a small issue as explained at the very bottom). Helium-3 is produced solely through fusion reactions, and lithium-6, lithium-7 and boron-11 (and boron-10) will be produced by melting down the corresponding isotope items in the Metal Melter, but I have not yet added the recipes for said items (I will do soon). All of the fusion reaction products correspond directly to the real-life products of such reactions.

The Neutron Irradiator is another way to produce more tritium by bombarding lithium-6 or boron-10 with neutrons. Each reaction produces tritium and helium-4, but as boron-10 is heavier, it produces more. A legitimate real-life reaction can be achieved by bombarding lithium-7 with neutrons, but this reaction is not in the mod as neutrons are also produced, which would make producing tritium too easy - you could just cycle the neutrons round.

Helium-4 can't be formed from helium-3 and a neutron, as helium-4 is far too stable. Instead, the helium-3 and neutron would react to form tritium and hydrogen, but it seems I forgot to add that recipe, so bear with me :P

I was just experimenting with the fusion reactor, and for some reason, some of the products for particular combos are a little messed up (the ones where the same fuel is used for both inputs), so that's another thing I need to work on. For example, the hydrogen-hydrogen reaction should produce only deuterium, but for some reason it's producing helium-3 and neutrons...

**Comment by CJL48** [comment]
I was trying to use Helium straight from the helium accumulator. So no, my problem is that I was trying to use a fluid that was not a valid fusion reactor fuel.

**Comment by turbodiesel4598** [comment]
Ah, ok :)
